name: DocHTML -- Build and Deploy

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
          .github/workflows/dependencies/documentation.sh
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx==5.0.0 sphinx_rtd_theme # breathe -- not using breathe at the moment
          python3 -m pip install -I docutils==0.16  # Downgrade docutils so that bullet points render properly with Sphinx

      - name: Build Docs
        run: |
          ./Docs/BuildDocs.sh

      - name: Check links
        run: |
          cd Docs/sphinx_doc
          make SPHINXOPTS="-v -W --keep-going" NO_DOXYGEN=TRUE linkcheck

      - name: Deploy to Webpage
        if: github.event_name == 'push' && github.repository == 'erf-model/ERF' && github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: erf-model/docs
          branch: main # The branch the action should deploy to.
          folder: Docs/doxygen_output/html # The folder the action should deploy.
          commit-message: "Deployed from erf-model/ERF"
