name: Linux GCC

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
  cancel-in-progress: true

jobs:
  library:
    name: GNU@9.3 C++17 Release
    runs-on: ubuntu-20.04
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependencies
      run: Submodules/AMReX/.github/workflows/dependencies/dependencies.sh

    - name: Configure Project and Generate Build System
      run: |
        cmake \
          -B${{runner.workspace}}/ERF/build \
          -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/ERF/install \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DERF_DIM:STRING=3 \
          -DERF_ENABLE_MPI:BOOL=ON \
          -DERF_ENABLE_TESTS:BOOL=ON \
          -DERF_ENABLE_ALL_WARNINGS:BOOL=ON \
          -DERF_ENABLE_FCOMPARE:BOOL=ON \
          ${{github.workspace}};

    - name: Compile and Link
      run: |
        cmake --build ${{runner.workspace}}/ERF/build --parallel 2 --verbose

 #  - name: CMake Tests # see file ERF/Tests/CTestList.cmake
 #    run: |
 #      ctest -L regression -VV
 #    working-directory: ${{runner.workspace}}/ERF/build

    name: GNU@9.3 C++17 Release
    runs-on: ubuntu-20.04
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependencies
      run: Submodules/AMReX/.github/workflows/dependencies/dependencies.sh

    - name: Configure Project and Generate Build System
      run: |
        cmake \
          -B${{runner.workspace}}/ERF/build \
          -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/ERF/install \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DERF_DIM:STRING=3 \
          -DERF_ENABLE_MPI:BOOL=OFF \
          -DERF_ENABLE_TESTS:BOOL=ON \
          -DERF_ENABLE_ALL_WARNINGS:BOOL=ON \
          -DERF_ENABLE_FCOMPARE:BOOL=ON \
          ${{github.workspace}};

    - name: Compile and Link
      run: |
        cmake --build ${{runner.workspace}}/ERF/build --parallel 2 --verbose

    - name: CMake Tests # see file ERF/Tests/CTestList.cmake
      run: |
        ctest -L regression -VV
      working-directory: ${{runner.workspace}}/ERF/build